version: '3.8'

services:
  
  # Main Server Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    container_name: server
    command: sh /app/start.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

  # FFmpeg Server Service
  ffmpeg_server:
    build:
      context: ./ffmpeg_server
      dockerfile: Dockerfile
      target: development
    container_name: ffmpeg_server
    command: yarn dev
    ports:
      - "3001:3001"
      - "9230:9230"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ffmpeg_server:/app
      - /app/node_modules
    user: root
    networks:
      - app-network

  # Client Service
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: production
    container_name: client
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search: .
    depends_on:
      - server
      - ffmpeg_server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dynamodb_data: