version: '3.8'

services:
  
  # Main Server Service
  server:
    build:
      context: ./server/api
      dockerfile: Dockerfile
      target: production
    container_name: server
    command: sh /app/start.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

  # FFmpeg Server Service
  ffmpeg:
    build:
      context: ./server/ffmpeg
      dockerfile: Dockerfile
      target: development
    container_name: ffmpeg
    command: yarn dev
    ports:
      - "3001:3001"
      - "9230:9230"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server/ffmpeg:/app
      - /app/node_modules
    user: root
    networks:
      - app-network

  # Client Service
  client:
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
      target: production
    container_name: client
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_search: .
    depends_on:
      - server
      - ffmpeg
    networks:
      - app-network

  base:
    image: fretstop-base:latest
    # Using sleep infinity to keep the container running
    command: sleep infinity
    # Add any ports you might want to expose for inspection
    ports:
      - "8080:8080"  # Adjust port as needed
    # Add any volumes if needed for inspection
    volumes:
      - ./:/app  # Mount current directory to /app in container

networks:
  app-network:
    driver: bridge

volumes:
  dynamodb_data: