# Use root/example as user/password credentials
version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - app-network

  # Main Server Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongodb:27017
      - SERVICE_NAME=server
    depends_on:
      - mongodb
    networks:
      - app-network

  # FFmpeg Server Service
  ffmpeg_server:
    build:
      context: ./ffmpeg_server
      dockerfile: Dockerfile
    container_name: ffmpeg_server
    ports:
      - "3001:3001"
    volumes:
      - ./ffmpeg_server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongodb:27017
      - SERVICE_NAME=ffmpeg_server
    depends_on:
      - mongodb
    networks:
      - app-network

  # Service Discovery (Consul for local development)
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -server -bootstrap -ui -client=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: